### PR TITLE
Bump version to 1.1.2

### PR DESCRIPTION
**Pull request by kaapstorm**
Bumps version to 1.1.2, and also tries to apply recent changes/conventions to packaging.

cc @Rohit25negi

### CODE REVIEW

**Comment by dannyroberts** [comment]
@kaapstorm excerpted from your email to me
> I followed https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/ (last updated this month). I tested building it, and installing it. I stopped at "The PyPI Staging Server". 

Did you end up testing it on the pypi staging server or did you stop before that? Just want to make sure we test any changes to our packaging before releasing

**Comment by kaapstorm** [comment]
Sorry for the ambiguity. No, I did not test on test.pypi.org.

**Comment by dannyroberts** [comment]
@kaapstorm I did a quick test (just that the package deployed was installable and I could import and use `memoized.memoized`) and then released it to pypi: https://pypi.org/project/dimagi-memoized/1.1.2/

It should now be possible to install it with `pip install memoized==1.1.2` or the like

**Comment by kaapstorm** [comment]
Thank you @dannyroberts!

**Pull request merged**
